### ISSUE TITLE
AutomaThemely on Ubuntu 19.04 (Python3.7)

### ISSUE THREAD

**Issue by astridos2go** [C2N14/AutomaThemely#19]
I recently installed Automa Themely on my Ubuntu 19.04 release. However, every time I attempt to launch, it does not launch. When launching from the terminal it gives the message: 
`bash: /usr/local/bin/automathemely: /usr/bin/python3.6: bad interpreter: No such file or directory`. 

I am guessing this is because Ubuntu 19.04 comes with Python 3.7 installed as opposed to python 3.6. Is there any way to be able to use Python 3.7 instead, or do I need to install 3.6. Or is there something else I am completely missing?

**Comment by rdnlsmith** [comment]
I also ran into problems on 19.04. Running `automathemely --manage` gives me the output below.

I was going to try to fix it, but I don't work with Python much and I haven't figured out how to run it from source yet :grimacing:

```
Traceback (most recent call last):
  File "/usr/local/bin/automathemely", line 11, in <module>
    load_entry_point('AutomaThemely==1.3', 'console_scripts', 'automathemely')()
  File "/usr/local/lib/python3.6/dist-packages/automathemely/bin/run.py", line 80, in main
    automathemely.autoth_tools.argmanager.main(user_settings)
  File "/usr/local/lib/python3.6/dist-packages/automathemely/autoth_tools/argmanager.py", line 99, in main
    from . import settsmanager
  File "/usr/local/lib/python3.6/dist-packages/automathemely/autoth_tools/settsmanager.py", line 2, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/automathemely", line 11, in <module>
    load_entry_point('AutomaThemely==1.3', 'console_scripts', 'automathemely')()
  File "/usr/local/lib/python3.6/dist-packages/automathemely/bin/run.py", line 80, in main
    automathemely.autoth_tools.argmanager.main(user_settings)
  File "/usr/local/lib/python3.6/dist-packages/automathemely/autoth_tools/argmanager.py", line 99, in main
    from . import settsmanager
  File "/usr/local/lib/python3.6/dist-packages/automathemely/autoth_tools/settsmanager.py", line 2, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'
```

**Comment by rdnlsmith** [comment]
@blumn2 I was looking at other issues just now, and I discovered via #14 that [haywirephoenix](https://github.com/haywirephoenix) has a [build for 3.7](https://github.com/haywirephoenix/AutomaThemely/releases/tag/v1.3) which seems to be working for me.

**Comment by C2N14** [comment]
Ah, I'll add an option for python 3.7 on the next release :)

**Comment by arian81** [comment]
Ubuntu 20.04 is coming with python 3.8 and we still don't have support for python 3.7 . what's going on and why no one is working on this project

**Comment by C2N14** [comment]
> 
> 
> Ubuntu 20.04 is coming with python 3.8 and we still don't have support for python 3.7 . what's going on and why no one is working on this project

I'm truly sorry. I've been awfully busy with school and other personal matters this past year or so and I'm afraid I have neglected this project.
I hope I can find some extra time during this period to be productive, though I can't promise anything :(

**Comment by mijorus** [comment]
> Ubuntu 20.04 is coming with python 3.8 and we still don't have support for python 3.7 . what's going on and why no one is working on this project

you have to run again the .package.sh and add `declare -a python_versions=("3.8")
`

it worked for me in Ubuntu 19.04

**Comment by Mennaruuk** [comment]
Can you explain more in steps how I can do that please?
