### ISSUE TITLE
Program won't open

### ISSUE THREAD

**Issue by jordihoven** [C2N14/AutomaThemely#30]
I downloaded python3.5-automathemely_1.3_all.deb and installed it using Eddy. The app icon shows up but clicking it has no effect.

**Comment by Ospeto** [comment]
I am having that problem on manjaro latest version too. Please guide me how to fix it. 

Traceback (most recent call last):
  File "/usr/bin/automathemely", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'schedule' distribution was not found and is required by AutomaThemely

**Comment by jordi-7** [comment]
> I am having that problem on manjaro latest version too. Please guide me how to fix it.
> 
> Traceback (most recent call last):
> File "/usr/bin/automathemely", line 6, in
> from pkg_resources import load_entry_point
> File "/usr/lib/python3.8/site-packages/pkg_resources/**init**.py", line 3252, in
> def _initialize_master_working_set():
> File "/usr/lib/python3.8/site-packages/pkg_resources/**init**.py", line 3235, in _call_aside
> f(*args, **kwargs)
> File "/usr/lib/python3.8/site-packages/pkg_resources/**init**.py", line 3264, in _initialize_master_working_set
> working_set = WorkingSet._build_master()
> File "/usr/lib/python3.8/site-packages/pkg_resources/**init**.py", line 583, in _build_master
> ws.require(**requires**)
> File "/usr/lib/python3.8/site-packages/pkg_resources/**init**.py", line 900, in require
> needed = self.resolve(parse_requirements(requirements))
> File "/usr/lib/python3.8/site-packages/pkg_resources/**init**.py", line 786, in resolve
> raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'schedule' distribution was not found and is required by AutomaThemely

Same issue here, on antergos

**Comment by jordi-7** [comment]
I manually reinstalled the dependencies but I am now stuck on this:

ImportError: cannot import name 'Location' from 'astral' (/home/jordi/.local/lib/python3.8/site-packages/astral/__init__.py)

**Comment by jordi-7** [comment]
Solved it by uninstalling astral and installing a specific version:

pip3 uninstall astral
pip3 install astral==1.10.1

Now automathemely starts without any issues.

**Comment by C2N14** [comment]
Seems like it is failing to install the `scheduler` dependency, I'm not really sure why though.
Can you install it through `pip3 install scheduler`?
