### ISSUE TITLE
AutomaThemely does not open on Manjaro 20.2

### ISSUE THREAD

**Issue by Mennaruuk** [C2N14/AutomaThemely#50]
```
Traceback (most recent call last):
File "/usr/bin/automathemely", line 33, in <module>
sys.exit(load_entry_point('AutomaThemely==1.3', 'console_scripts', 'automathemely')())
File "/usr/lib/python3.8/site-packages/automathemely/bin/run.py", line 29, in main
from automathemely.autoth_tools import argmanager, extratools, envspecific, updsuntimes
File "/usr/lib/python3.8/site-packages/automathemely/autoth_tools/updsuntimes.py", line 8, in <module>
from astral import Location
ImportError: cannot import name 'Location' from 'astral' (/usr/lib/python3.8/site-packages/astral/__init__.py)
```

**Comment by lambdakilo** [comment]
Solution [found](https://github.com/C2N14/AutomaThemely/pull/36). Bug in the usage of Astral, not in Manjaro 20.2. I believe you can close this now.

**Comment by Mennaruuk** [comment]
THANK YOU!
