### ISSUE TITLE
Downloaded latest verion no-deps for Linux Mint 19 (based on Ubuntu 18) and can't run

### ISSUE THREAD

**Issue by ppazos** [C2N14/AutomaThemely#52]
Used this distro https://github.com/C2N14/AutomaThemely/releases/download/v1.3/python3.6-no_deps-automathemely_1.3_all.deb

It seems like a code bug or a dependency problem, so not sure if no-deps is really no-deps :)

```
$ automathemely --manage
Traceback (most recent call last):
  File "/usr/local/bin/automathemely", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tzlocal' distribution was not found and is required by AutomaThemely

```

**Comment by ppazos** [comment]
It seems all deps doesn't have all deps.

After:

```
sudo apt install python3-pip
pip3 install tzlocal
pip3 install schedule
pip3 install astral
```

I got:

```
Traceback (most recent call last):
  File "/usr/local/bin/automathemely", line 11, in <module>
    load_entry_point('AutomaThemely==1.3', 'console_scripts', 'automathemely')()
  File "/usr/local/lib/python3.6/dist-packages/automathemely/bin/run.py", line 29, in main
    from automathemely.autoth_tools import argmanager, extratools, envspecific, updsuntimes
  File "/usr/local/lib/python3.6/dist-packages/automathemely/autoth_tools/updsuntimes.py", line 8, in <module>
    from astral import Location
ImportError: cannot import name 'Location'

```

I guess you need to be a python expert to run this app :)

**Comment by odannis** [comment]
https://github.com/C2N14/AutomaThemely/pull/51
